import './Button/Button.stories'
import './Welcome/Welcome.stories'
import './View/View.stories'
import './Text/Text.stories'
import './TextInput/TextInput.stories'
import './Image/Image.stories'
import './ActivityIndicator/ActivityIndicator.stories'
import './Modal/Modal.stories'
